version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sec_database_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_sec_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg_sec_data:
    external: true
